### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by fengsky401** [IDEA-opensource/DAB-DETR#45]
When I setup deformable multi head attention, report the error as below:

> nvcc fatal   : Unsupported gpu architecture 'compute_86'
> Traceback (most recent call last):
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
>     env=env)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "setup.py", line 72, in <module>
>     cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/command/build_ext.py", line 340, in run
>     self.build_extensions()
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
>     build_ext.build_extensions(self)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
>     self._build_extensions_serial()
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
>     self.build_extension(ext)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
>     _build_ext.build_extension(self, ext)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
>     depends=ext.depends)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 565, in unix_wrap_ninja_compile
>     with_cuda=with_cuda)
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
>     error_prefix='Error compiling objects for extension')
>   File "/data/queenie_liu/anaconda3/envs/mmTrans/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error compiling objects for extension

**Comment by SlongLiu** [comment]
It seems like a problem with your environment. Can you provide the env and the command you used?
